// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e44ae6b9-5edc-4dcd-8f80-3cad51d56764";

const char SSID[]               = "StoodLemming7";    // Network SSID (name)
const char PASS[]               = "Faiez123";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "m?tT1802inT0sHGR1#NLmlOKF";    // Secret device password

void onSwitchChange();

CloudHeartRate bPM;
CloudLight lED;
int steps;
bool _switch_;
CloudTime rTC;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(bPM, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lED, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(steps, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(_switch_, READWRITE, ON_CHANGE, onSwitchChange);
  ArduinoCloud.addProperty(rTC, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
